//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> BrigadeID { get; set; }
    
        public virtual Brigades Brigades { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
